### PR TITLE
small tweak for ELF v2 weights

### PR DESCRIPTION
**Pull request by sethtroisi**

### CODE REVIEW

**Comment by alreadydone** [comment]
Will the weight file converted using the old script be problematic?

**Comment by sethtroisi** [comment]
it just didn't convert for me.

**Comment by alreadydone** [comment]
I didn't do it myself (still haven't installed pytorch) but two other people succeeded (but didn't mention any error) so I assumed anything was working fine...

**Comment by l1t1** [comment]
I got same errmsg when tested, then the fix works
need install torch first, as https://pytorch.org/ says
```
C:\Python37\Scripts>pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl
Collecting torch==1.0.1 from https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl
  Downloading https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl (73.6MB)
    100% |████████████████████████████████| 73.6MB 137kB/s
Installing collected packages: torch
  The scripts convert-caffe2-to-onnx.exe and convert-onnx-to-caffe2.exe are installed in 'c:\python37\Scripts
not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-loc
Successfully installed torch-1.0.1
You are using pip version 18.1, however version 19.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Python37\Scripts>d:

D:\>C:\Python37\python elf_convert.py elfv2.bin
Traceback (most recent call last):
  File "elf_convert.py", line 44, in <module>
    b = convert_block(state, 'init_conv')
  File "elf_convert.py", line 13, in convert_block
    weight = np.array(t[name + '.0.weight'])
KeyError: 'init_conv.0.weight'

D:\>C:\Python37\python elf_convert.py elfv2.bin

```

**Comment by l1t1** [comment]
and the result
elfv2_converted_weights.txt	(text/plain) - 338819184 bytes
SHA-256	2c08d7e95253c07c7fdbfeebdc5b93b4834014eb783ccfb16297d0a64fb7b4ff
while version, maybe he use a linux version
elfv2	(n/a) - 338819005 bytes
SHA-256	05dbca157002b9fd618145d22803beae0f7e4015af48ac50f246b9316e315544

**Comment by l1t1** [comment]
I use the code at https://github.com/leela-zero/leela-zero/issues/2164 to compare them
they are identical
D:\>pypy2-v6.0.0-win32\pypy fc2.py elfv2 elfv2_converted_weights.txt
usage fc.py weight1 weight2

(1, 2.0, 2.0)
(41472, 0.0005230751854604164, 0.0005230751854604164)
(256, 0.003795922028685111, 0.003795922028685111)
(256, 0.005646072384322444, 0.005646072384322444)
(256, 0.022002905201196337, 0.022002905201196337)
...
(1, 0.24896823, 0.24896823)
Weight file difference L2-norm: 0.0

**Comment by l1t1** [comment]
why elf native windows engine cannot use elfv2.bin (https://github.com/pytorch/ELF/issues/133#issuecomment-463852764),but lz can use the converted version

**Pull request merged**
