### PR TITLE
I had problems with the build when qtdir wasn't set

### PR DESCRIPTION
**Pull request by iopq**
Found out I needed not only to install Qt, but also tell VS where it is

### CODE REVIEW

**Comment by AncalagonX** [comment]
Perhaps a custom Build Error Message could be generated that informs the user when this occurs?

**Comment by iopq** [comment]
Yes, that would probably be ideal. It should be mentioned in the readme anyway.

**Comment by gcp** [comment]
>It should be mentioned in the readme anyway.

https://github.com/leela-zero/leela-zero/tree/master/autogtp

However, the leela-zero build shouldn't fail if you don't have Qt, that's a bug.

>Perhaps a custom Build Error Message could be generated that informs the user when this occurs?

I think this is sensible, pointing out autogtp won't be compiled because the requirements aren't met.

**Comment by iopq** [comment]
@gcp it's not clear, is the main page telling you how to build auto-gtp AND leela-zero or just one of them?

Because it switches between telling you how to compile auto-gtp on Linux back to just doing leela-zero on Windows fooling you into thinking that's the only instructions

**Pull request closed without merging**
